In [4]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor

df = pd.DataFrame({
    "Height": [1.6,1.6,1.5,1.8, 1.5, 1.4],
    "Color":["Blue","Green","Blue","Red","Green","Blue"],
    "Gender":["M","F","F","M","M","F"],
    "Weight":[88,76,56,73,77,57]})

In [5]:
df

   Height  Color Gender  Weight
0     1.6   Blue      M      88
1     1.6  Green      F      76
2     1.5   Blue      F      56
3     1.8    Red      M      73
4     1.5  Green      M      77
5     1.4   Blue      F      57

In [6]:
df = pd.get_dummies(df)
df

   Height  Weight  Color_Blue  Color_Green  Color_Red  Gender_F  Gender_M
0     1.6      88        True        False      False     False      True
1     1.6      76       False         True      False      True     False
2     1.5      56        True        False      False      True     False
3     1.8      73       False        False       True     False      True
4     1.5      77       False         True      False     False      True
5     1.4      57        True        False      False      True     False

In [7]:
df

   Height  Weight  Color_Blue  Color_Green  Color_Red  Gender_F  Gender_M
0     1.6      88        True        False      False     False      True
1     1.6      76       False         True      False      True     False
2     1.5      56        True        False      False      True     False
3     1.8      73       False        False       True     False      True
4     1.5      77       False         True      False     False      True
5     1.4      57        True        False      False      True     False

In [8]:
x = df.loc[:,df.columns != 'Weight']
y = df['Weight']
F0 = np.mean(y)
print(F0)

71.16666666666667

In [9]:
r1 = y - F0
print(r1)

0    16.833333
1     4.833333
2   -15.166667
3     1.833333
4     5.833333
5   -14.166667
Name: Weight, dtype: float64

In [10]:
tree1  = DecisionTreeRegressor (random_state = 433, max_depth = 1)
r1_fit = tree1.fit(x, r1) # 독립변수로 잔차를 모형화 한다.
gamma1  = r1_fit.predict(x)
print ('잔차 예측값', gamma1)

잔차 예측값 [ 8.16666667 -8.16666667 -8.16666667  8.16666667  8.16666667 -8.16666667]

In [11]:
eta = 0.1 # learning rate
F1 = F0 + eta * gamma1
print ('0번째 예측값:{}'.format(F0))
print ('첫번째 예측값:{}'.format(F1))

0번째 예측값:71.16666666666667
첫번째 예측값:[71.98333333 70.35       70.35       71.98333333 71.98333333 70.35      ]

In [12]:
import copy
F_new = np.mean(y) #초기화 모형
tree = DecisionTreeRegressor(random_state=433, max_depth =1) #약한 학습기
eta = 0.1 #학습률
T = 100
models = []
for t in range(T):
    print(str(t+1)+'번째 업데이트')
    F_old = F_new
    r     = y - F_old        # 잔차
    r_fit = tree.fit(x,r)    # 잔차 적합
    gamma = r_fit.predict(x)
    models.append(copy.deepcopy(r_fit))
    print('잔차 예측값:{}'.format(np.round(gamma,2)))

    F_new = F_old + eta * gamma # 새로운 예측값

    print('예측값:{}'.format(np.round(F_new,2)))

1번째 업데이트
잔차 예측값:[ 8.17 -8.17 -8.17  8.17  8.17 -8.17]
예측값:[71.98 70.35 70.35 71.98 71.98 70.35]
2번째 업데이트
잔차 예측값:[ 7.56  7.56 -7.56  7.56 -7.56 -7.56]
예측값:[72.74 71.11 69.59 72.74 71.23 69.59]
3번째 업데이트
잔차 예측값:[ 7.1 -7.1 -7.1  7.1  7.1 -7.1]
예측값:[73.45 70.4  68.88 73.45 71.94 68.88]
4번째 업데이트
잔차 예측값:[ 6.57  6.57 -6.57  6.57 -6.57 -6.57]
예측값:[74.11 71.05 68.23 74.11 71.28 68.23]
5번째 업데이트
잔차 예측값:[ 6.17 -6.17 -6.17  6.17  6.17 -6.17]
예측값:[74.72 70.44 67.61 74.72 71.9  67.61]
6번째 업데이트
잔차 예측값:[ 5.71  5.71 -5.71  5.71 -5.71 -5.71]
예측값:[75.29 71.01 67.04 75.29 71.33 67.04]
7번째 업데이트
잔차 예측값:[ 5.36 -5.36 -5.36  5.36  5.36 -5.36]
예측값:[75.83 70.47 66.5  75.83 71.86 66.5 ]
8번째 업데이트
잔차 예측값:[ 4.96  4.96 -4.96  4.96 -4.96 -4.96]
예측값:[76.33 70.97 66.01 76.33 71.37 66.01]
9번째 업데이트
잔차 예측값:[ 4.66 -4.66 -4.66  4.66  4.66 -4.66]
예측값:[76.79 70.5  65.54 76.79 71.83 65.54]
10번째 업데이트
잔차 예측값:[ 4.31  4.31 -4.31  4.31 -4.31 -4.31]
예측값:[77.22 70.93 65.11 77.22 71.4  65.11]
11번째 업데이트
잔차 예측값:[ 4.05 -4.05 -4.05  4.05  4.05 -4.05]
예측값:[77.63 70.53 64.71 77.63 71.81 64.71]
12번째 업데이트
잔차 예측값:[-2.67  5.33 -2.67 -2.67  5.33 -2.67]
예측값:[77.36 71.06 64.44 77.36 72.34 64.44]
13번째 업데이트
잔차 예측값:[ 3.74  3.74 -3.74  3.74 -3.74 -3.74]
예측값:[77.73 71.43 64.07 77.73 71.97 64.07]
14번째 업데이트
잔차 예측값:[ 3.52 -3.52 -3.52  3.52  3.52 -3.52]
예측값:[78.09 71.08 63.71 78.09 72.32 63.71]
15번째 업데이트
잔차 예측값:[-2.4  4.8 -2.4 -2.4  4.8 -2.4]
예측값:[77.85 71.56 63.47 77.85 72.8  63.47]
16번째 업데이트
잔차 예측값:[ 3.25  3.25 -3.25  3.25 -3.25 -3.25]
예측값:[78.17 71.89 63.15 78.17 72.47 63.15]
17번째 업데이트
잔차 예측값:[ 3.06 -3.06 -3.06  3.06  3.06 -3.06]
예측값:[78.48 71.58 62.84 78.48 72.78 62.84]
18번째 업데이트
잔차 예측값:[-2.16  4.32 -2.16 -2.16  4.32 -2.16]
예측값:[78.26 72.01 62.63 78.26 73.21 62.63]
19번째 업데이트
잔차 예측값:[ 2.82  2.82 -2.82  2.82 -2.82 -2.82]
예측값:[78.54 72.29 62.34 78.54 72.93 62.34]
20번째 업데이트
잔차 예측값:[-1.94  3.89 -1.94 -1.94  3.89 -1.94]
예측값:[78.35 72.68 62.15 78.35 73.32 62.15]
21번째 업데이트
잔차 예측값:[ 2.66 -2.66 -2.66  2.66  2.66 -2.66]
예측값:[78.62 72.42 61.88 78.62 73.59 61.88]
22번째 업데이트
잔차 예측값:[ 1.12  1.12  1.12 -5.62  1.12  1.12]
예측값:[78.73 72.53 62.   78.05 73.7  62.  ]
23번째 업데이트
잔차 예측값:[ 2.56  2.56 -2.56  2.56 -2.56 -2.56]
예측값:[78.98 72.79 61.74 78.31 73.44 61.74]
24번째 업데이트
잔차 예측값:[ 2.42 -2.42 -2.42  2.42  2.42 -2.42]
예측값:[79.23 72.54 61.5  78.55 73.68 61.5 ]
25번째 업데이트
잔차 예측값:[ 1.11  1.11  1.11 -5.55  1.11  1.11]
예측값:[79.34 72.65 61.61 78.   73.79 61.61]
26번째 업데이트
잔차 예측값:[ 2.34  2.34 -2.34  2.34 -2.34 -2.34]
예측값:[79.57 72.89 61.37 78.23 73.56 61.37]
27번째 업데이트
잔차 예측값:[ 1.05  1.05  1.05 -5.23  1.05  1.05]
예측값:[79.68 72.99 61.48 77.71 73.67 61.48]
28번째 업데이트
잔차 예측값:[ 2.32 -2.32 -2.32  2.32  2.32 -2.32]
예측값:[79.91 72.76 61.25 77.94 73.9  61.25]
29번째 업데이트
잔차 예측값:[-1.59  3.17 -1.59 -1.59  3.17 -1.59]
예측값:[79.75 73.08 61.09 77.78 74.21 61.09]
30번째 업데이트
잔차 예측값:[ 0.96  0.96  0.96 -4.78  0.96  0.96]
예측값:[79.84 73.17 61.18 77.3  74.31 61.18]
31번째 업데이트
잔차 예측값:[ 2.23  2.23 -2.23  2.23 -2.23 -2.23]
예측값:[80.07 73.4  60.96 77.53 74.09 60.96]
32번째 업데이트
잔차 예측값:[ 2.11 -2.11 -2.11  2.11  2.11 -2.11]
예측값:[80.28 73.19 60.75 77.74 74.3  60.75]
33번째 업데이트
잔차 예측값:[ 0.95  0.95  0.95 -4.74  0.95  0.95]
예측값:[80.37 73.28 60.85 77.26 74.39 60.85]
34번째 업데이트
잔차 예측값:[ 2.03  2.03 -2.03  2.03 -2.03 -2.03]
예측값:[80.58 73.48 60.64 77.47 74.19 60.64]
35번째 업데이트
잔차 예측값:[ 0.89  0.89  0.89 -4.47  0.89  0.89]
예측값:[80.66 73.57 60.73 77.02 74.28 60.73]
36번째 업데이트
잔차 예측값:[ 2.01 -2.01 -2.01  2.01  2.01 -2.01]
예측값:[80.87 73.37 60.53 77.22 74.48 60.53]
37번째 업데이트
잔차 예측값:[ 0.84  0.84  0.84 -4.22  0.84  0.84]
예측값:[80.95 73.46 60.62 76.8  74.56 60.62]
38번째 업데이트
잔차 예측값:[ 1.93  1.93 -1.93  1.93 -1.93 -1.93]
예측값:[81.14 73.65 60.42 76.99 74.37 60.42]
39번째 업데이트
잔차 예측값:[ 1.83 -1.83 -1.83  1.83  1.83 -1.83]
예측값:[81.33 73.47 60.24 77.17 74.55 60.24]
40번째 업데이트
잔차 예측값:[ 0.83  0.83  0.83 -4.17  0.83  0.83]
예측값:[81.41 73.55 60.32 76.76 74.64 60.32]
41번째 업데이트
잔차 예측값:[ 1.76  1.76 -1.76  1.76 -1.76 -1.76]
예측값:[81.59 73.73 60.15 76.93 74.46 60.15]
42번째 업데이트
잔차 예측값:[ 0.79  0.79  0.79 -3.93  0.79  0.79]
예측값:[81.66 73.8  60.23 76.54 74.54 60.23]
43번째 업데이트
잔차 예측값:[ 1.75 -1.75 -1.75  1.75  1.75 -1.75]
예측값:[81.84 73.63 60.05 76.71 74.72 60.05]
44번째 업데이트
잔차 예측값:[ 0.74  0.74  0.74 -3.71  0.74  0.74]
예측값:[81.91 73.7  60.12 76.34 74.79 60.12]
45번째 업데이트
잔차 예측값:[ 1.68  1.68 -1.68  1.68 -1.68 -1.68]
예측값:[82.08 73.87 59.96 76.51 74.62 59.96]
46번째 업데이트
잔차 예측값:[ 1.59 -1.59 -1.59  1.59  1.59 -1.59]
예측값:[82.24 73.71 59.8  76.67 74.78 59.8 ]
47번째 업데이트
잔차 예측값:[ 0.73  0.73  0.73 -3.67  0.73  0.73]
예측값:[82.32 73.78 59.87 76.3  74.85 59.87]
48번째 업데이트
잔차 예측값:[-1.09  2.18 -1.09 -1.09  2.18 -1.09]
예측값:[82.21 74.   59.76 76.19 75.07 59.76]
49번째 업데이트
잔차 예측값:[ 1.53  1.53 -1.53  1.53 -1.53 -1.53]
예측값:[82.36 74.16 59.61 76.35 74.92 59.61]
50번째 업데이트
잔차 예측값:[ 0.67  0.67  0.67 -3.35  0.67  0.67]
예측값:[82.43 74.22 59.68 76.01 74.99 59.68]
51번째 업데이트
잔차 예측값:[ 1.52 -1.52 -1.52  1.52  1.52 -1.52]
예측값:[82.58 74.07 59.52 76.17 75.14 59.52]
52번째 업데이트
잔차 예측값:[ 0.63  0.63  0.63 -3.17  0.63  0.63]
예측값:[82.64 74.13 59.59 75.85 75.2  59.59]
53번째 업데이트
잔차 예측값:[ 1.46  1.46 -1.46  1.46 -1.46 -1.46]
예측값:[82.79 74.28 59.44 75.99 75.06 59.44]
54번째 업데이트
잔차 예측값:[ 1.39 -1.39 -1.39  1.39  1.39 -1.39]
예측값:[82.93 74.14 59.3  76.13 75.2  59.3 ]
55번째 업데이트
잔차 예측값:[ 0.63  0.63  0.63 -3.13  0.63  0.63]
예측값:[82.99 74.2  59.36 75.82 75.26 59.36]
56번째 업데이트
잔차 예측값:[ 1.33  1.33 -1.33  1.33 -1.33 -1.33]
예측값:[83.12 74.34 59.23 75.95 75.13 59.23]
57번째 업데이트
잔차 예측값:[ 0.59  0.59  0.59 -2.95  0.59  0.59]
예측값:[83.18 74.4  59.29 75.66 75.18 59.29]
58번째 업데이트
잔차 예측값:[ 1.33 -1.33 -1.33  1.33  1.33 -1.33]
예측값:[83.31 74.26 59.16 75.79 75.32 59.16]
59번째 업데이트
잔차 예측값:[ 0.56  0.56  0.56 -2.79  0.56  0.56]
예측값:[83.37 74.32 59.21 75.51 75.37 59.21]
60번째 업데이트
잔차 예측값:[ 1.27  1.27 -1.27  1.27 -1.27 -1.27]
예측값:[83.5  74.45 59.09 75.64 75.25 59.09]
61번째 업데이트
잔차 예측값:[ 1.21 -1.21 -1.21  1.21  1.21 -1.21]
예측값:[83.62 74.32 58.97 75.76 75.37 58.97]
62번째 업데이트
잔차 예측값:[ 0.55  0.55  0.55 -2.76  0.55  0.55]
예측값:[83.67 74.38 59.02 75.48 75.42 59.02]
63번째 업데이트
잔차 예측값:[ 1.15  1.15 -1.15  1.15 -1.15 -1.15]
예측값:[83.79 74.5  58.91 75.6  75.31 58.91]
64번째 업데이트
잔차 예측값:[ 0.52  0.52  0.52 -2.6   0.52  0.52]
예측값:[83.84 74.55 58.96 75.34 75.36 58.96]
65번째 업데이트
잔차 예측값:[ 1.15 -1.15 -1.15  1.15  1.15 -1.15]
예측값:[83.96 74.43 58.84 75.45 75.47 58.84]
66번째 업데이트
잔차 예측값:[ 0.49  0.49  0.49 -2.45  0.49  0.49]
예측값:[84.   74.48 58.89 75.21 75.52 58.89]
67번째 업데이트
잔차 예측값:[ 1.1  1.1 -1.1  1.1 -1.1 -1.1]
예측값:[84.11 74.59 58.78 75.32 75.41 58.78]
68번째 업데이트
잔차 예측값:[-0.75  1.5  -0.75 -0.75  1.5  -0.75]
예측값:[84.04 74.74 58.71 75.24 75.56 58.71]
69번째 업데이트
잔차 예측값:[ 1.05 -1.05 -1.05  1.05  1.05 -1.05]
예측값:[84.14 74.64 58.6  75.35 75.67 58.6 ]
70번째 업데이트
잔차 예측값:[ 0.47  0.47  0.47 -2.35  0.47  0.47]
예측값:[84.19 74.68 58.65 75.11 75.71 58.65]
71번째 업데이트
잔차 예측값:[ 1.  1. -1.  1. -1. -1.]
예측값:[84.29 74.78 58.55 75.21 75.61 58.55]
72번째 업데이트
잔차 예측값:[ 0.44  0.44  0.44 -2.21  0.44  0.44]
예측값:[84.34 74.83 58.59 74.99 75.66 58.59]
73번째 업데이트
잔차 예측값:[ 1. -1. -1.  1.  1. -1.]
예측값:[84.44 74.73 58.49 75.09 75.76 58.49]
74번째 업데이트
잔차 예측값:[ 0.42  0.42  0.42 -2.09  0.42  0.42]
예측값:[84.48 74.77 58.53 74.88 75.8  58.53]
75번째 업데이트
잔차 예측값:[ 0.96  0.96 -0.96  0.96 -0.96 -0.96]
예측값:[84.57 74.86 58.44 74.98 75.7  58.44]
76번째 업데이트
잔차 예측값:[ 0.91 -0.91 -0.91  0.91  0.91 -0.91]
예측값:[84.67 74.77 58.35 75.07 75.8  58.35]
77번째 업데이트
잔차 예측값:[ 0.41  0.41  0.41 -2.07  0.41  0.41]
예측값:[84.71 74.81 58.39 74.86 75.84 58.39]
78번째 업데이트
잔차 예측값:[ 0.87  0.87 -0.87  0.87 -0.87 -0.87]
예측값:[84.79 74.9  58.3  74.95 75.75 58.3 ]
79번째 업데이트
잔차 예측값:[ 0.39  0.39  0.39 -1.95  0.39  0.39]
예측값:[84.83 74.94 58.34 74.76 75.79 58.34]
80번째 업데이트
잔차 예측값:[ 0.87 -0.87 -0.87  0.87  0.87 -0.87]
예측값:[84.92 74.85 58.25 74.84 75.88 58.25]
81번째 업데이트
잔차 예측값:[ 0.37  0.37  0.37 -1.84  0.37  0.37]
예측값:[84.96 74.89 58.29 74.66 75.91 58.29]
82번째 업데이트
잔차 예측값:[ 0.83  0.83 -0.83  0.83 -0.83 -0.83]
예측값:[85.04 74.97 58.21 74.74 75.83 58.21]
83번째 업데이트
잔차 예측값:[ 0.8 -0.8 -0.8  0.8  0.8 -0.8]
예측값:[85.12 74.89 58.13 74.82 75.91 58.13]
84번째 업데이트
잔차 예측값:[ 0.36  0.36  0.36 -1.82  0.36  0.36]
예측값:[85.16 74.93 58.16 74.64 75.95 58.16]
85번째 업데이트
잔차 예측값:[ 0.76  0.76 -0.76  0.76 -0.76 -0.76]
예측값:[85.23 75.01 58.09 74.72 75.87 58.09]
86번째 업데이트
잔차 예측값:[ 0.34  0.34  0.34 -1.72  0.34  0.34]
예측값:[85.27 75.04 58.12 74.54 75.91 58.12]
87번째 업데이트
잔차 예측값:[ 0.76 -0.76 -0.76  0.76  0.76 -0.76]
예측값:[85.34 74.96 58.05 74.62 75.98 58.05]
88번째 업데이트
잔차 예측값:[-0.51  1.03 -0.51 -0.51  1.03 -0.51]
예측값:[85.29 75.07 57.99 74.57 76.08 57.99]
89번째 업데이트
잔차 예측값:[ 0.31  0.31  0.31 -1.57  0.31  0.31]
예측값:[85.32 75.1  58.03 74.41 76.12 58.03]
90번째 업데이트
잔차 예측값:[ 0.72  0.72 -0.72  0.72 -0.72 -0.72]
예측값:[85.39 75.17 57.95 74.48 76.04 57.95]
91번째 업데이트
잔차 예측값:[ 0.69 -0.69 -0.69  0.69  0.69 -0.69]
예측값:[85.46 75.1  57.88 74.55 76.11 57.88]
92번째 업데이트
잔차 예측값:[ 0.31  0.31  0.31 -1.55  0.31  0.31]
예측값:[85.5  75.13 57.92 74.4  76.14 57.92]
93번째 업데이트
잔차 예측값:[ 0.66  0.66 -0.66  0.66 -0.66 -0.66]
예측값:[85.56 75.2  57.85 74.46 76.08 57.85]
94번째 업데이트
잔차 예측값:[ 0.29  0.29  0.29 -1.46  0.29  0.29]
예측값:[85.59 75.23 57.88 74.32 76.11 57.88]
95번째 업데이트
잔차 예측값:[ 0.66 -0.66 -0.66  0.66  0.66 -0.66]
예측값:[85.66 75.16 57.81 74.38 76.17 57.81]
96번째 업데이트
잔차 예측값:[ 0.28  0.28  0.28 -1.38  0.28  0.28]
예측값:[85.68 75.19 57.84 74.25 76.2  57.84]
97번째 업데이트
잔차 예측값:[ 0.63  0.63 -0.63  0.63 -0.63 -0.63]
예측값:[85.75 75.25 57.78 74.31 76.14 57.78]
98번째 업데이트
잔차 예측값:[ 0.6 -0.6 -0.6  0.6  0.6 -0.6]
예측값:[85.81 75.19 57.72 74.37 76.2  57.72]
99번째 업데이트
잔차 예측값:[ 0.27  0.27  0.27 -1.37  0.27  0.27]
예측값:[85.83 75.22 57.74 74.23 76.23 57.74]
100번째 업데이트
잔차 예측값:[ 0.57  0.57 -0.57  0.57 -0.57 -0.57]
예측값:[85.89 75.28 57.69 74.29 76.17 57.69]

In [ ]:
x_new = x.loc[0:0,:]
x_new

   Height  Color_Blue  Color_Green  Color_Red  Gender_F  Gender_M
0     1.6           1            0          0         0         1

In [ ]:
x_new['Height'] = 2.0

<ipython-input-11-1aee925754de>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_new['Height'] = 2.0

In [ ]:
x_new

   Height  Color_Blue  Color_Green  Color_Red  Gender_F  Gender_M
0     2.0           1            0          0         0         1

In [ ]:
F_old = F0
for i in range(T):
    F_new = F_old + eta * models[i].predict(x_new)
    F_old = F_new
    print(F_new)

[71.98333333]
[72.73944444]
[73.44924074]
[74.10608086]
[74.72300286]
[75.2935949]
[75.82980497]
[76.32546414]
[76.79153122]
[77.22208891]
[77.62719736]
[77.36053069]
[77.73452899]
[78.08665999]
[77.84665999]
[78.17152076]
[78.47760996]
[78.26160996]
[78.54378168]
[78.34938168]
[78.61545624]
[78.72776537]
[78.98408168]
[79.22623582]
[79.33728344]
[79.57100108]
[79.67561829]
[79.90733291]
[79.74877161]
[79.84439016]
[80.06703579]
[80.27771929]
[80.37244257]
[80.57527318]
[80.66458075]
[80.86583796]
[80.95023991]
[81.14344984]
[81.32658119]
[81.41006978]
[81.58620319]
[81.66486559]
[81.84002779]
[81.91432719]
[82.0823047]
[82.24178138]
[82.31519992]
[82.20619076]
[82.35939649]
[82.42635711]
[82.57881717]
[82.64213093]
[82.78796152]
[82.92664593]
[82.98931862]
[83.1222106]
[83.18127386]
[83.31383369]
[83.36964182]
[83.49631308]
[83.61697537]
[83.67214935]
[83.78764881]
[83.83961539]
[83.95507552]
[84.00415464]
[84.11436005]
[84.03945372]
[84.14460223]
[84.1915824]
[84.29196033]
[84.33625004]
[84.43666476]
[84.47853378]
[84.57414264]
[84.66551583]
[84.7069376]
[84.79408197]
[84.83310445]
[84.92047993]
[84.95734767]
[85.04045411]
[85.12000861]
[85.15644279]
[85.23223019]
[85.2665367]
[85.34268357]
[85.29132745]
[85.32269912]
[85.39493737]
[85.46419878]
[85.49526328]
[85.56107544]
[85.59034974]
[85.65652515]
[85.68419552]
[85.74691509]
[85.80714934]
[85.83451175]
[85.89168779]